version: "3.9"
services:
  db-mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sparkyapp
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - 3306:3306
  db-redis:
    image: redis
    ports:
      - 6379:6379
  backend-spring:
    build: ../sparky
    platform: linux/amd64
    ports:
      - 4040:4040
    links:
      - db-mysql
      - db-redis
    depends_on:
      - db-mysql
      - db-redis